spring:
  application:
    name: demo_thymeleaf
  datasource:
    url: jdbc:mysql://localhost:3306/db_demo_thymeleaf?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

server:
  port: 8080
